language: java
jdk:
- openjdk8

env:
  global:
    - TEST="sp4"
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - sudo apt-get -y install jq
  - pip install --user awscli
  - aws configure
    AWS Access Key ID [None]: $ACCESS_KEY
    AWS Secret Access Key [None]: $SECRET_KEY
    Default region name [None]: eu-north-1
    Default output format [None]: json
before_script:
  - ls -lah
  - google-chrome-stable --version
  - netstat -vatn

stages:
- prepare
- compile
- test
- reports

jobs:
  include:
  - stage: prepare
    name: Start tests
    script:
    - echo ------------------- START TESTS ----------------------
    - gradle --version #it is helpful

  - stage: test
    name: Run tests - sp4
    script:
    - ./gradlew :sp4:test --tests "com.sp4.uitest.tests.TestMainPage" -Dparams=--headless,--verbose --info

  - stage: reports
    name: Deploy allure reports to s3
    script:
    - npm install -g allure-commandline
    - npm install -g netlify-cli
    - allure --version
    - allure generate -c sp4/build/allure-results -o reports/allure-results-html
    - aws s3 sync reports/allure-results-html s3://sp4.allure-results/
after_failure:
- echo "Build was failed"
after_success:
- echo "Build was successful"
after_script:
- source reports.sh
- grubAllureResults
- du -d 1 -h ./
- ls -la
# extra time during long builds
install:
- travis_wait
- ./gradlew assemble
